name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: actions/hello-world-javascript-action@master
      with:
        who-to-greet: 'Mona the Octocat'
